apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: auth
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 3000
          name: auth-http
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: AUTH
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: REDIS_URI
        - name: RSA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: jwt
              key: RSA_PRIVATE_KEY
        - name: RSA_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt
              key: RSA_PUBLIC_KEY
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_REFRESH_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: google
              key: GOOGLE_CALLBACK_URL
              optional: true
        - name: CLIENT_URL
          valueFrom:
            secretKeyRef:
              name: google
              key: CLIENT_URL
              optional: true
